// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi opus47

    Schemes:
      https
    Host: opus47.goodwu.net
    BasePath: /
    Version: 1.0.0
    License: Apache 2.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
