// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "opus47",
    "license": {
      "name": "Apache 2.0"
    },
    "version": "1.0.0"
  },
  "host": "opus47.goodwu.net",
  "basePath": "/",
  "paths": {
    "/composers": {
      "get": {
        "description": "List composers",
        "summary": "List composers",
        "responses": {
          "200": {
            "description": "List of composers",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Composer"
              }
            }
          }
        }
      }
    },
    "/composers/{id}": {
      "get": {
        "description": "Get composer information",
        "summary": "Get composer information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Composer information",
            "schema": {
              "$ref": "#/definitions/Composer"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a composer",
        "summary": "Add or update a composer",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The composer to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Composer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Composer updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a composer",
        "summary": "Delete a composer",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Composer deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/keys": {
      "get": {
        "description": "List keys",
        "summary": "List keys",
        "responses": {
          "200": {
            "description": "List of keys",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Performance"
              }
            }
          }
        }
      }
    },
    "/keys/{id}": {
      "get": {
        "description": "Get key information",
        "summary": "Get key information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Key information",
            "schema": {
              "$ref": "#/definitions/Key"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a key",
        "summary": "Add or update a key",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The key to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Key"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Key updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a key",
        "summary": "Delete a key",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Key deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/musicians": {
      "get": {
        "description": "List musicians",
        "summary": "List musicians",
        "responses": {
          "200": {
            "description": "List of musicians",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Musician"
              }
            }
          }
        }
      }
    },
    "/musicians/{id}": {
      "get": {
        "description": "Get musician information",
        "summary": "Get musician information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Musician information",
            "schema": {
              "$ref": "#/definitions/Musician"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a musician",
        "summary": "Add or update a musician",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The musician to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Musician"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Musician updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a musician",
        "summary": "Delete a musician",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Musician deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/parts": {
      "get": {
        "description": "List parts",
        "summary": "List parts",
        "responses": {
          "200": {
            "description": "List of parts",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Part"
              }
            }
          }
        }
      }
    },
    "/parts/{id}": {
      "get": {
        "description": "Get part information",
        "summary": "Get part information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Part information",
            "schema": {
              "$ref": "#/definitions/Part"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a part",
        "summary": "Add or update a part",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The part to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Part"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Part updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a part",
        "summary": "Delete a part",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Part deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/performances": {
      "get": {
        "description": "List performances",
        "summary": "List performances",
        "responses": {
          "200": {
            "description": "List of performances",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Performance"
              }
            }
          }
        }
      },
      "put": {
        "description": "Add or update a performance",
        "summary": "Add or update a performance",
        "parameters": [
          {
            "description": "The performance to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Performance"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Performance updated"
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/performances/{id}": {
      "get": {
        "description": "Get performance information",
        "summary": "Get performance information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Performance information",
            "schema": {
              "$ref": "#/definitions/Performance"
            }
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "delete": {
        "description": "Delete a performance",
        "summary": "Delete a performance",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Performance deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/pieces": {
      "get": {
        "description": "List pieces",
        "summary": "List pieces",
        "responses": {
          "200": {
            "description": "List of pieces",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Piece"
              }
            }
          }
        }
      },
      "put": {
        "description": "Add or update a piece",
        "summary": "Add or update a piece",
        "parameters": [
          {
            "description": "The piece to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Piece"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Piece updated"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    },
    "/pieces/search": {
      "get": {
        "description": "Search pieces",
        "summary": "Search pieces",
        "parameters": [
          {
            "type": "string",
            "description": "The search text",
            "name": "text",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of pieces",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Piece"
              }
            }
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    },
    "/pieces/{id}": {
      "get": {
        "description": "Get pieces information",
        "summary": "Get piece information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Piece information",
            "schema": {
              "$ref": "#/definitions/Piece"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      },
      "post": {
        "description": "Update a piece",
        "summary": "Update a piece",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The piece to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Piece"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Piece updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a piece",
        "summary": "Delete a piece",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Piece deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/pieces/{id}/performances": {
      "get": {
        "description": "Get all the performances of a piece",
        "summary": "Get all the performances of a piece",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Piece information",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Performance"
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    },
    "/recordings": {
      "get": {
        "description": "List recordings",
        "summary": "List recordings",
        "responses": {
          "200": {
            "description": "List of recordings",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Recording"
              }
            }
          }
        }
      },
      "put": {
        "description": "Add or update a recording",
        "consumes": [
          "multipart/form-data"
        ],
        "summary": "Add or update a recording",
        "parameters": [
          {
            "type": "string",
            "description": "performance name",
            "name": "performance",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "description": "movement number",
            "name": "movement",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "description": "recording file",
            "name": "file",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Recording updated"
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/recordings/{id}": {
      "get": {
        "description": "Get recording information",
        "summary": "Get recording information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Recording information",
            "schema": {
              "$ref": "#/definitions/Recording"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a recording",
        "summary": "Delete a recording",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Recording deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "definitions": {
    "Composer": {
      "properties": {
        "first": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "last": {
          "type": "string"
        },
        "middle": {
          "type": "string"
        }
      }
    },
    "ErrorMessage": {
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Key": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Movement": {
      "properties": {
        "id": {
          "type": "string"
        },
        "number": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Musician": {
      "properties": {
        "first": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "last": {
          "type": "string"
        },
        "middle": {
          "type": "string"
        }
      }
    },
    "Part": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Performance": {
      "properties": {
        "date": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "performers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Performer"
          }
        },
        "pieceId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Performer": {
      "properties": {
        "id": {
          "type": "string"
        },
        "musician": {
          "type": "string"
        },
        "part": {
          "type": "string"
        }
      }
    },
    "Piece": {
      "properties": {
        "catalog": {
          "type": "string"
        },
        "composer": {
          "$ref": "#/definitions/Composer"
        },
        "id": {
          "type": "string"
        },
        "key": {
          "$ref": "#/definitions/Key"
        },
        "movements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Movement"
          }
        },
        "number": {
          "type": "integer"
        },
        "parts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Part"
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Recording": {
      "properties": {
        "file": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "movement": {
          "type": "string"
        },
        "performance": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "opus47",
    "license": {
      "name": "Apache 2.0"
    },
    "version": "1.0.0"
  },
  "host": "opus47.goodwu.net",
  "basePath": "/",
  "paths": {
    "/composers": {
      "get": {
        "description": "List composers",
        "summary": "List composers",
        "responses": {
          "200": {
            "description": "List of composers",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Composer"
              }
            }
          }
        }
      }
    },
    "/composers/{id}": {
      "get": {
        "description": "Get composer information",
        "summary": "Get composer information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Composer information",
            "schema": {
              "$ref": "#/definitions/Composer"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a composer",
        "summary": "Add or update a composer",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The composer to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Composer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Composer updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a composer",
        "summary": "Delete a composer",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Composer deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/keys": {
      "get": {
        "description": "List keys",
        "summary": "List keys",
        "responses": {
          "200": {
            "description": "List of keys",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Performance"
              }
            }
          }
        }
      }
    },
    "/keys/{id}": {
      "get": {
        "description": "Get key information",
        "summary": "Get key information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Key information",
            "schema": {
              "$ref": "#/definitions/Key"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a key",
        "summary": "Add or update a key",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The key to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Key"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Key updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a key",
        "summary": "Delete a key",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Key deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/musicians": {
      "get": {
        "description": "List musicians",
        "summary": "List musicians",
        "responses": {
          "200": {
            "description": "List of musicians",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Musician"
              }
            }
          }
        }
      }
    },
    "/musicians/{id}": {
      "get": {
        "description": "Get musician information",
        "summary": "Get musician information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Musician information",
            "schema": {
              "$ref": "#/definitions/Musician"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a musician",
        "summary": "Add or update a musician",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The musician to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Musician"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Musician updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a musician",
        "summary": "Delete a musician",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Musician deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/parts": {
      "get": {
        "description": "List parts",
        "summary": "List parts",
        "responses": {
          "200": {
            "description": "List of parts",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Part"
              }
            }
          }
        }
      }
    },
    "/parts/{id}": {
      "get": {
        "description": "Get part information",
        "summary": "Get part information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Part information",
            "schema": {
              "$ref": "#/definitions/Part"
            }
          }
        }
      },
      "put": {
        "description": "Add or update a part",
        "summary": "Add or update a part",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The part to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Part"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Part updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a part",
        "summary": "Delete a part",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Part deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/performances": {
      "get": {
        "description": "List performances",
        "summary": "List performances",
        "responses": {
          "200": {
            "description": "List of performances",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Performance"
              }
            }
          }
        }
      },
      "put": {
        "description": "Add or update a performance",
        "summary": "Add or update a performance",
        "parameters": [
          {
            "description": "The performance to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Performance"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Performance updated"
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/performances/{id}": {
      "get": {
        "description": "Get performance information",
        "summary": "Get performance information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Performance information",
            "schema": {
              "$ref": "#/definitions/Performance"
            }
          },
          "500": {
            "description": "Internal error"
          }
        }
      },
      "delete": {
        "description": "Delete a performance",
        "summary": "Delete a performance",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Performance deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/pieces": {
      "get": {
        "description": "List pieces",
        "summary": "List pieces",
        "responses": {
          "200": {
            "description": "List of pieces",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Piece"
              }
            }
          }
        }
      },
      "put": {
        "description": "Add or update a piece",
        "summary": "Add or update a piece",
        "parameters": [
          {
            "description": "The piece to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Piece"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Piece updated"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ErrorMessage"
            }
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    },
    "/pieces/search": {
      "get": {
        "description": "Search pieces",
        "summary": "Search pieces",
        "parameters": [
          {
            "type": "string",
            "description": "The search text",
            "name": "text",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of pieces",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Piece"
              }
            }
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    },
    "/pieces/{id}": {
      "get": {
        "description": "Get pieces information",
        "summary": "Get piece information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Piece information",
            "schema": {
              "$ref": "#/definitions/Piece"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      },
      "post": {
        "description": "Update a piece",
        "summary": "Update a piece",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "The piece to add or update",
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Piece"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Piece updated"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "description": "Delete a piece",
        "summary": "Delete a piece",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Piece deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/pieces/{id}/performances": {
      "get": {
        "description": "Get all the performances of a piece",
        "summary": "Get all the performances of a piece",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Piece information",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Performance"
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Error"
          }
        }
      }
    },
    "/recordings": {
      "get": {
        "description": "List recordings",
        "summary": "List recordings",
        "responses": {
          "200": {
            "description": "List of recordings",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Recording"
              }
            }
          }
        }
      },
      "put": {
        "description": "Add or update a recording",
        "consumes": [
          "multipart/form-data"
        ],
        "summary": "Add or update a recording",
        "parameters": [
          {
            "type": "string",
            "description": "performance name",
            "name": "performance",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "description": "movement number",
            "name": "movement",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "description": "recording file",
            "name": "file",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Recording updated"
          },
          "403": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal error"
          }
        }
      }
    },
    "/recordings/{id}": {
      "get": {
        "description": "Get recording information",
        "summary": "Get recording information",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Recording information",
            "schema": {
              "$ref": "#/definitions/Recording"
            }
          }
        }
      },
      "delete": {
        "description": "Delete a recording",
        "summary": "Delete a recording",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Recording deleted"
          },
          "403": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "definitions": {
    "Composer": {
      "properties": {
        "first": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "last": {
          "type": "string"
        },
        "middle": {
          "type": "string"
        }
      }
    },
    "ErrorMessage": {
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Key": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Movement": {
      "properties": {
        "id": {
          "type": "string"
        },
        "number": {
          "type": "integer"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Musician": {
      "properties": {
        "first": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "last": {
          "type": "string"
        },
        "middle": {
          "type": "string"
        }
      }
    },
    "Part": {
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Performance": {
      "properties": {
        "date": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "performers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Performer"
          }
        },
        "pieceId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Performer": {
      "properties": {
        "id": {
          "type": "string"
        },
        "musician": {
          "type": "string"
        },
        "part": {
          "type": "string"
        }
      }
    },
    "Piece": {
      "properties": {
        "catalog": {
          "type": "string"
        },
        "composer": {
          "$ref": "#/definitions/Composer"
        },
        "id": {
          "type": "string"
        },
        "key": {
          "$ref": "#/definitions/Key"
        },
        "movements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Movement"
          }
        },
        "number": {
          "type": "integer"
        },
        "parts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Part"
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Recording": {
      "properties": {
        "file": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "movement": {
          "type": "string"
        },
        "performance": {
          "type": "string"
        }
      }
    }
  }
}`))
}
