// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteMusiciansIDOKCode is the HTTP code returned for type DeleteMusiciansIDOK
const DeleteMusiciansIDOKCode int = 200

/*DeleteMusiciansIDOK Musician deleted

swagger:response deleteMusiciansIdOK
*/
type DeleteMusiciansIDOK struct {
}

// NewDeleteMusiciansIDOK creates DeleteMusiciansIDOK with default headers values
func NewDeleteMusiciansIDOK() *DeleteMusiciansIDOK {
	return &DeleteMusiciansIDOK{}
}

// WriteResponse to the client
func (o *DeleteMusiciansIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteMusiciansIDForbiddenCode is the HTTP code returned for type DeleteMusiciansIDForbidden
const DeleteMusiciansIDForbiddenCode int = 403

/*DeleteMusiciansIDForbidden Unauthorized

swagger:response deleteMusiciansIdForbidden
*/
type DeleteMusiciansIDForbidden struct {
}

// NewDeleteMusiciansIDForbidden creates DeleteMusiciansIDForbidden with default headers values
func NewDeleteMusiciansIDForbidden() *DeleteMusiciansIDForbidden {
	return &DeleteMusiciansIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteMusiciansIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
