// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRecordingsIDOKCode is the HTTP code returned for type DeleteRecordingsIDOK
const DeleteRecordingsIDOKCode int = 200

/*DeleteRecordingsIDOK Recording deleted

swagger:response deleteRecordingsIdOK
*/
type DeleteRecordingsIDOK struct {
}

// NewDeleteRecordingsIDOK creates DeleteRecordingsIDOK with default headers values
func NewDeleteRecordingsIDOK() *DeleteRecordingsIDOK {

	return &DeleteRecordingsIDOK{}
}

// WriteResponse to the client
func (o *DeleteRecordingsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteRecordingsIDForbiddenCode is the HTTP code returned for type DeleteRecordingsIDForbidden
const DeleteRecordingsIDForbiddenCode int = 403

/*DeleteRecordingsIDForbidden Unauthorized

swagger:response deleteRecordingsIdForbidden
*/
type DeleteRecordingsIDForbidden struct {
}

// NewDeleteRecordingsIDForbidden creates DeleteRecordingsIDForbidden with default headers values
func NewDeleteRecordingsIDForbidden() *DeleteRecordingsIDForbidden {

	return &DeleteRecordingsIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteRecordingsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
