// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteRecordingsIDHandlerFunc turns a function with the right signature into a delete recordings ID handler
type DeleteRecordingsIDHandlerFunc func(DeleteRecordingsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRecordingsIDHandlerFunc) Handle(params DeleteRecordingsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteRecordingsIDHandler interface for that can handle valid delete recordings ID params
type DeleteRecordingsIDHandler interface {
	Handle(DeleteRecordingsIDParams) middleware.Responder
}

// NewDeleteRecordingsID creates a new http.Handler for the delete recordings ID operation
func NewDeleteRecordingsID(ctx *middleware.Context, handler DeleteRecordingsIDHandler) *DeleteRecordingsID {
	return &DeleteRecordingsID{Context: ctx, Handler: handler}
}

/*DeleteRecordingsID swagger:route DELETE /recordings/{id} deleteRecordingsId

Delete a recording

Delete a recording

*/
type DeleteRecordingsID struct {
	Context *middleware.Context
	Handler DeleteRecordingsIDHandler
}

func (o *DeleteRecordingsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRecordingsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
