// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePerformancesIDOKCode is the HTTP code returned for type DeletePerformancesIDOK
const DeletePerformancesIDOKCode int = 200

/*DeletePerformancesIDOK Performance deleted

swagger:response deletePerformancesIdOK
*/
type DeletePerformancesIDOK struct {
}

// NewDeletePerformancesIDOK creates DeletePerformancesIDOK with default headers values
func NewDeletePerformancesIDOK() *DeletePerformancesIDOK {
	return &DeletePerformancesIDOK{}
}

// WriteResponse to the client
func (o *DeletePerformancesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeletePerformancesIDForbiddenCode is the HTTP code returned for type DeletePerformancesIDForbidden
const DeletePerformancesIDForbiddenCode int = 403

/*DeletePerformancesIDForbidden Unauthorized

swagger:response deletePerformancesIdForbidden
*/
type DeletePerformancesIDForbidden struct {
}

// NewDeletePerformancesIDForbidden creates DeletePerformancesIDForbidden with default headers values
func NewDeletePerformancesIDForbidden() *DeletePerformancesIDForbidden {
	return &DeletePerformancesIDForbidden{}
}

// WriteResponse to the client
func (o *DeletePerformancesIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
