// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePiecesIDHandlerFunc turns a function with the right signature into a delete pieces ID handler
type DeletePiecesIDHandlerFunc func(DeletePiecesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePiecesIDHandlerFunc) Handle(params DeletePiecesIDParams) middleware.Responder {
	return fn(params)
}

// DeletePiecesIDHandler interface for that can handle valid delete pieces ID params
type DeletePiecesIDHandler interface {
	Handle(DeletePiecesIDParams) middleware.Responder
}

// NewDeletePiecesID creates a new http.Handler for the delete pieces ID operation
func NewDeletePiecesID(ctx *middleware.Context, handler DeletePiecesIDHandler) *DeletePiecesID {
	return &DeletePiecesID{Context: ctx, Handler: handler}
}

/*DeletePiecesID swagger:route DELETE /pieces/{id} deletePiecesId

Delete a piece

Delete a piece

*/
type DeletePiecesID struct {
	Context *middleware.Context
	Handler DeletePiecesIDHandler
}

func (o *DeletePiecesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePiecesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
