// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteComposersIDOKCode is the HTTP code returned for type DeleteComposersIDOK
const DeleteComposersIDOKCode int = 200

/*DeleteComposersIDOK Composer deleted

swagger:response deleteComposersIdOK
*/
type DeleteComposersIDOK struct {
}

// NewDeleteComposersIDOK creates DeleteComposersIDOK with default headers values
func NewDeleteComposersIDOK() *DeleteComposersIDOK {

	return &DeleteComposersIDOK{}
}

// WriteResponse to the client
func (o *DeleteComposersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteComposersIDForbiddenCode is the HTTP code returned for type DeleteComposersIDForbidden
const DeleteComposersIDForbiddenCode int = 403

/*DeleteComposersIDForbidden Unauthorized

swagger:response deleteComposersIdForbidden
*/
type DeleteComposersIDForbidden struct {
}

// NewDeleteComposersIDForbidden creates DeleteComposersIDForbidden with default headers values
func NewDeleteComposersIDForbidden() *DeleteComposersIDForbidden {

	return &DeleteComposersIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteComposersIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
