// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePerformancesIDHandlerFunc turns a function with the right signature into a delete performances ID handler
type DeletePerformancesIDHandlerFunc func(DeletePerformancesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePerformancesIDHandlerFunc) Handle(params DeletePerformancesIDParams) middleware.Responder {
	return fn(params)
}

// DeletePerformancesIDHandler interface for that can handle valid delete performances ID params
type DeletePerformancesIDHandler interface {
	Handle(DeletePerformancesIDParams) middleware.Responder
}

// NewDeletePerformancesID creates a new http.Handler for the delete performances ID operation
func NewDeletePerformancesID(ctx *middleware.Context, handler DeletePerformancesIDHandler) *DeletePerformancesID {
	return &DeletePerformancesID{Context: ctx, Handler: handler}
}

/*DeletePerformancesID swagger:route DELETE /performances/{id} deletePerformancesId

Delete a performance

Delete a performance

*/
type DeletePerformancesID struct {
	Context *middleware.Context
	Handler DeletePerformancesIDHandler
}

func (o *DeletePerformancesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePerformancesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
