// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePartsIDHandlerFunc turns a function with the right signature into a delete parts ID handler
type DeletePartsIDHandlerFunc func(DeletePartsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePartsIDHandlerFunc) Handle(params DeletePartsIDParams) middleware.Responder {
	return fn(params)
}

// DeletePartsIDHandler interface for that can handle valid delete parts ID params
type DeletePartsIDHandler interface {
	Handle(DeletePartsIDParams) middleware.Responder
}

// NewDeletePartsID creates a new http.Handler for the delete parts ID operation
func NewDeletePartsID(ctx *middleware.Context, handler DeletePartsIDHandler) *DeletePartsID {
	return &DeletePartsID{Context: ctx, Handler: handler}
}

/*DeletePartsID swagger:route DELETE /parts/{id} deletePartsId

Delete a part

Delete a part

*/
type DeletePartsID struct {
	Context *middleware.Context
	Handler DeletePartsIDHandler
}

func (o *DeletePartsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePartsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
