// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteKeysIDHandlerFunc turns a function with the right signature into a delete keys ID handler
type DeleteKeysIDHandlerFunc func(DeleteKeysIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteKeysIDHandlerFunc) Handle(params DeleteKeysIDParams) middleware.Responder {
	return fn(params)
}

// DeleteKeysIDHandler interface for that can handle valid delete keys ID params
type DeleteKeysIDHandler interface {
	Handle(DeleteKeysIDParams) middleware.Responder
}

// NewDeleteKeysID creates a new http.Handler for the delete keys ID operation
func NewDeleteKeysID(ctx *middleware.Context, handler DeleteKeysIDHandler) *DeleteKeysID {
	return &DeleteKeysID{Context: ctx, Handler: handler}
}

/*DeleteKeysID swagger:route DELETE /keys/{id} deleteKeysId

Delete a key

Delete a key

*/
type DeleteKeysID struct {
	Context *middleware.Context
	Handler DeleteKeysIDHandler
}

func (o *DeleteKeysID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteKeysIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
