// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePiecesIDOKCode is the HTTP code returned for type DeletePiecesIDOK
const DeletePiecesIDOKCode int = 200

/*DeletePiecesIDOK Piece deleted

swagger:response deletePiecesIdOK
*/
type DeletePiecesIDOK struct {
}

// NewDeletePiecesIDOK creates DeletePiecesIDOK with default headers values
func NewDeletePiecesIDOK() *DeletePiecesIDOK {

	return &DeletePiecesIDOK{}
}

// WriteResponse to the client
func (o *DeletePiecesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeletePiecesIDForbiddenCode is the HTTP code returned for type DeletePiecesIDForbidden
const DeletePiecesIDForbiddenCode int = 403

/*DeletePiecesIDForbidden Unauthorized

swagger:response deletePiecesIdForbidden
*/
type DeletePiecesIDForbidden struct {
}

// NewDeletePiecesIDForbidden creates DeletePiecesIDForbidden with default headers values
func NewDeletePiecesIDForbidden() *DeletePiecesIDForbidden {

	return &DeletePiecesIDForbidden{}
}

// WriteResponse to the client
func (o *DeletePiecesIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
