// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPiecesSearchParams creates a new GetPiecesSearchParams object
// no default values defined in spec.
func NewGetPiecesSearchParams() GetPiecesSearchParams {

	return GetPiecesSearchParams{}
}

// GetPiecesSearchParams contains all the bound params for the get pieces search operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetPiecesSearch
type GetPiecesSearchParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The search text
	  In: query
	*/
	Text *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPiecesSearchParams() beforehand.
func (o *GetPiecesSearchParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qText, qhkText, _ := qs.GetOK("text")
	if err := o.bindText(qText, qhkText, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindText binds and validates parameter Text from query.
func (o *GetPiecesSearchParams) bindText(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Text = &raw

	return nil
}
