// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetPartsIDOKCode is the HTTP code returned for type GetPartsIDOK
const GetPartsIDOKCode int = 200

/*GetPartsIDOK Part information

swagger:response getPartsIdOK
*/
type GetPartsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Part `json:"body,omitempty"`
}

// NewGetPartsIDOK creates GetPartsIDOK with default headers values
func NewGetPartsIDOK() *GetPartsIDOK {
	return &GetPartsIDOK{}
}

// WithPayload adds the payload to the get parts Id o k response
func (o *GetPartsIDOK) WithPayload(payload *models.Part) *GetPartsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get parts Id o k response
func (o *GetPartsIDOK) SetPayload(payload *models.Part) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPartsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
