// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/opus47/cloud/api/models"
)

// GetRecordingsOKCode is the HTTP code returned for type GetRecordingsOK
const GetRecordingsOKCode int = 200

/*GetRecordingsOK List of recordings

swagger:response getRecordingsOK
*/
type GetRecordingsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Recording `json:"body,omitempty"`
}

// NewGetRecordingsOK creates GetRecordingsOK with default headers values
func NewGetRecordingsOK() *GetRecordingsOK {

	return &GetRecordingsOK{}
}

// WithPayload adds the payload to the get recordings o k response
func (o *GetRecordingsOK) WithPayload(payload []*models.Recording) *GetRecordingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get recordings o k response
func (o *GetRecordingsOK) SetPayload(payload []*models.Recording) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecordingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Recording, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
