// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPerformancesHandlerFunc turns a function with the right signature into a get performances handler
type GetPerformancesHandlerFunc func(GetPerformancesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPerformancesHandlerFunc) Handle(params GetPerformancesParams) middleware.Responder {
	return fn(params)
}

// GetPerformancesHandler interface for that can handle valid get performances params
type GetPerformancesHandler interface {
	Handle(GetPerformancesParams) middleware.Responder
}

// NewGetPerformances creates a new http.Handler for the get performances operation
func NewGetPerformances(ctx *middleware.Context, handler GetPerformancesHandler) *GetPerformances {
	return &GetPerformances{Context: ctx, Handler: handler}
}

/*GetPerformances swagger:route GET /performances getPerformances

List performances

List performances

*/
type GetPerformances struct {
	Context *middleware.Context
	Handler GetPerformancesHandler
}

func (o *GetPerformances) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPerformancesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
