// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPartsIDHandlerFunc turns a function with the right signature into a get parts ID handler
type GetPartsIDHandlerFunc func(GetPartsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPartsIDHandlerFunc) Handle(params GetPartsIDParams) middleware.Responder {
	return fn(params)
}

// GetPartsIDHandler interface for that can handle valid get parts ID params
type GetPartsIDHandler interface {
	Handle(GetPartsIDParams) middleware.Responder
}

// NewGetPartsID creates a new http.Handler for the get parts ID operation
func NewGetPartsID(ctx *middleware.Context, handler GetPartsIDHandler) *GetPartsID {
	return &GetPartsID{Context: ctx, Handler: handler}
}

/*GetPartsID swagger:route GET /parts/{id} getPartsId

Get part information

Get part information

*/
type GetPartsID struct {
	Context *middleware.Context
	Handler GetPartsIDHandler
}

func (o *GetPartsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPartsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
