// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPerformancesIDHandlerFunc turns a function with the right signature into a get performances ID handler
type GetPerformancesIDHandlerFunc func(GetPerformancesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPerformancesIDHandlerFunc) Handle(params GetPerformancesIDParams) middleware.Responder {
	return fn(params)
}

// GetPerformancesIDHandler interface for that can handle valid get performances ID params
type GetPerformancesIDHandler interface {
	Handle(GetPerformancesIDParams) middleware.Responder
}

// NewGetPerformancesID creates a new http.Handler for the get performances ID operation
func NewGetPerformancesID(ctx *middleware.Context, handler GetPerformancesIDHandler) *GetPerformancesID {
	return &GetPerformancesID{Context: ctx, Handler: handler}
}

/*GetPerformancesID swagger:route GET /performances/{id} getPerformancesId

Get performance information

Get performance information

*/
type GetPerformancesID struct {
	Context *middleware.Context
	Handler GetPerformancesIDHandler
}

func (o *GetPerformancesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPerformancesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
