// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetKeysHandlerFunc turns a function with the right signature into a get keys handler
type GetKeysHandlerFunc func(GetKeysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKeysHandlerFunc) Handle(params GetKeysParams) middleware.Responder {
	return fn(params)
}

// GetKeysHandler interface for that can handle valid get keys params
type GetKeysHandler interface {
	Handle(GetKeysParams) middleware.Responder
}

// NewGetKeys creates a new http.Handler for the get keys operation
func NewGetKeys(ctx *middleware.Context, handler GetKeysHandler) *GetKeys {
	return &GetKeys{Context: ctx, Handler: handler}
}

/*GetKeys swagger:route GET /keys getKeys

List keys

List keys

*/
type GetKeys struct {
	Context *middleware.Context
	Handler GetKeysHandler
}

func (o *GetKeys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetKeysParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
