// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetPerformancesOKCode is the HTTP code returned for type GetPerformancesOK
const GetPerformancesOKCode int = 200

/*GetPerformancesOK List of performances

swagger:response getPerformancesOK
*/
type GetPerformancesOK struct {

	/*
	  In: Body
	*/
	Payload models.GetPerformancesOKBody `json:"body,omitempty"`
}

// NewGetPerformancesOK creates GetPerformancesOK with default headers values
func NewGetPerformancesOK() *GetPerformancesOK {
	return &GetPerformancesOK{}
}

// WithPayload adds the payload to the get performances o k response
func (o *GetPerformancesOK) WithPayload(payload models.GetPerformancesOKBody) *GetPerformancesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get performances o k response
func (o *GetPerformancesOK) SetPayload(payload models.GetPerformancesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPerformancesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetPerformancesOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
