// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPiecesIDPerformancesHandlerFunc turns a function with the right signature into a get pieces ID performances handler
type GetPiecesIDPerformancesHandlerFunc func(GetPiecesIDPerformancesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPiecesIDPerformancesHandlerFunc) Handle(params GetPiecesIDPerformancesParams) middleware.Responder {
	return fn(params)
}

// GetPiecesIDPerformancesHandler interface for that can handle valid get pieces ID performances params
type GetPiecesIDPerformancesHandler interface {
	Handle(GetPiecesIDPerformancesParams) middleware.Responder
}

// NewGetPiecesIDPerformances creates a new http.Handler for the get pieces ID performances operation
func NewGetPiecesIDPerformances(ctx *middleware.Context, handler GetPiecesIDPerformancesHandler) *GetPiecesIDPerformances {
	return &GetPiecesIDPerformances{Context: ctx, Handler: handler}
}

/*GetPiecesIDPerformances swagger:route GET /pieces/{id}/performances getPiecesIdPerformances

Get all the performances of a piece

Get all the performances of a piece

*/
type GetPiecesIDPerformances struct {
	Context *middleware.Context
	Handler GetPiecesIDPerformancesHandler
}

func (o *GetPiecesIDPerformances) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPiecesIDPerformancesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
