// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetKeysIDOKCode is the HTTP code returned for type GetKeysIDOK
const GetKeysIDOKCode int = 200

/*GetKeysIDOK Key information

swagger:response getKeysIdOK
*/
type GetKeysIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Key `json:"body,omitempty"`
}

// NewGetKeysIDOK creates GetKeysIDOK with default headers values
func NewGetKeysIDOK() *GetKeysIDOK {
	return &GetKeysIDOK{}
}

// WithPayload adds the payload to the get keys Id o k response
func (o *GetKeysIDOK) WithPayload(payload *models.Key) *GetKeysIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get keys Id o k response
func (o *GetKeysIDOK) SetPayload(payload *models.Key) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetKeysIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
