// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRecordingsHandlerFunc turns a function with the right signature into a get recordings handler
type GetRecordingsHandlerFunc func(GetRecordingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRecordingsHandlerFunc) Handle(params GetRecordingsParams) middleware.Responder {
	return fn(params)
}

// GetRecordingsHandler interface for that can handle valid get recordings params
type GetRecordingsHandler interface {
	Handle(GetRecordingsParams) middleware.Responder
}

// NewGetRecordings creates a new http.Handler for the get recordings operation
func NewGetRecordings(ctx *middleware.Context, handler GetRecordingsHandler) *GetRecordings {
	return &GetRecordings{Context: ctx, Handler: handler}
}

/*GetRecordings swagger:route GET /recordings getRecordings

List recordings

List recordings

*/
type GetRecordings struct {
	Context *middleware.Context
	Handler GetRecordingsHandler
}

func (o *GetRecordings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRecordingsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
