// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetPerformancesIDOKCode is the HTTP code returned for type GetPerformancesIDOK
const GetPerformancesIDOKCode int = 200

/*GetPerformancesIDOK Performance information

swagger:response getPerformancesIdOK
*/
type GetPerformancesIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Performance `json:"body,omitempty"`
}

// NewGetPerformancesIDOK creates GetPerformancesIDOK with default headers values
func NewGetPerformancesIDOK() *GetPerformancesIDOK {
	return &GetPerformancesIDOK{}
}

// WithPayload adds the payload to the get performances Id o k response
func (o *GetPerformancesIDOK) WithPayload(payload *models.Performance) *GetPerformancesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get performances Id o k response
func (o *GetPerformancesIDOK) SetPayload(payload *models.Performance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPerformancesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
