// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPartsHandlerFunc turns a function with the right signature into a get parts handler
type GetPartsHandlerFunc func(GetPartsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPartsHandlerFunc) Handle(params GetPartsParams) middleware.Responder {
	return fn(params)
}

// GetPartsHandler interface for that can handle valid get parts params
type GetPartsHandler interface {
	Handle(GetPartsParams) middleware.Responder
}

// NewGetParts creates a new http.Handler for the get parts operation
func NewGetParts(ctx *middleware.Context, handler GetPartsHandler) *GetParts {
	return &GetParts{Context: ctx, Handler: handler}
}

/*GetParts swagger:route GET /parts getParts

List parts

List parts

*/
type GetParts struct {
	Context *middleware.Context
	Handler GetPartsHandler
}

func (o *GetParts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPartsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
