// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetPiecesOKCode is the HTTP code returned for type GetPiecesOK
const GetPiecesOKCode int = 200

/*GetPiecesOK List of pieces

swagger:response getPiecesOK
*/
type GetPiecesOK struct {

	/*
	  In: Body
	*/
	Payload models.GetPiecesOKBody `json:"body,omitempty"`
}

// NewGetPiecesOK creates GetPiecesOK with default headers values
func NewGetPiecesOK() *GetPiecesOK {
	return &GetPiecesOK{}
}

// WithPayload adds the payload to the get pieces o k response
func (o *GetPiecesOK) WithPayload(payload models.GetPiecesOKBody) *GetPiecesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pieces o k response
func (o *GetPiecesOK) SetPayload(payload models.GetPiecesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPiecesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetPiecesOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
