// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetMusiciansIDOKCode is the HTTP code returned for type GetMusiciansIDOK
const GetMusiciansIDOKCode int = 200

/*GetMusiciansIDOK Musician information

swagger:response getMusiciansIdOK
*/
type GetMusiciansIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Musician `json:"body,omitempty"`
}

// NewGetMusiciansIDOK creates GetMusiciansIDOK with default headers values
func NewGetMusiciansIDOK() *GetMusiciansIDOK {
	return &GetMusiciansIDOK{}
}

// WithPayload adds the payload to the get musicians Id o k response
func (o *GetMusiciansIDOK) WithPayload(payload *models.Musician) *GetMusiciansIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get musicians Id o k response
func (o *GetMusiciansIDOK) SetPayload(payload *models.Musician) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMusiciansIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
