// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetComposersIDOKCode is the HTTP code returned for type GetComposersIDOK
const GetComposersIDOKCode int = 200

/*GetComposersIDOK Composer information

swagger:response getComposersIdOK
*/
type GetComposersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Composer `json:"body,omitempty"`
}

// NewGetComposersIDOK creates GetComposersIDOK with default headers values
func NewGetComposersIDOK() *GetComposersIDOK {
	return &GetComposersIDOK{}
}

// WithPayload adds the payload to the get composers Id o k response
func (o *GetComposersIDOK) WithPayload(payload *models.Composer) *GetComposersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get composers Id o k response
func (o *GetComposersIDOK) SetPayload(payload *models.Composer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComposersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
