// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/opus47/cloud/api/models"
)

// GetRecordingsIDOKCode is the HTTP code returned for type GetRecordingsIDOK
const GetRecordingsIDOKCode int = 200

/*GetRecordingsIDOK Recording information

swagger:response getRecordingsIdOK
*/
type GetRecordingsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Recording `json:"body,omitempty"`
}

// NewGetRecordingsIDOK creates GetRecordingsIDOK with default headers values
func NewGetRecordingsIDOK() *GetRecordingsIDOK {
	return &GetRecordingsIDOK{}
}

// WithPayload adds the payload to the get recordings Id o k response
func (o *GetRecordingsIDOK) WithPayload(payload *models.Recording) *GetRecordingsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get recordings Id o k response
func (o *GetRecordingsIDOK) SetPayload(payload *models.Recording) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecordingsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
