// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPiecesSearchHandlerFunc turns a function with the right signature into a get pieces search handler
type GetPiecesSearchHandlerFunc func(GetPiecesSearchParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPiecesSearchHandlerFunc) Handle(params GetPiecesSearchParams) middleware.Responder {
	return fn(params)
}

// GetPiecesSearchHandler interface for that can handle valid get pieces search params
type GetPiecesSearchHandler interface {
	Handle(GetPiecesSearchParams) middleware.Responder
}

// NewGetPiecesSearch creates a new http.Handler for the get pieces search operation
func NewGetPiecesSearch(ctx *middleware.Context, handler GetPiecesSearchHandler) *GetPiecesSearch {
	return &GetPiecesSearch{Context: ctx, Handler: handler}
}

/*GetPiecesSearch swagger:route GET /pieces/search getPiecesSearch

Search pieces

Search pieces

*/
type GetPiecesSearch struct {
	Context *middleware.Context
	Handler GetPiecesSearchHandler
}

func (o *GetPiecesSearch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPiecesSearchParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
