// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/opus47/cloud/api/models"
)

// GetPiecesSearchOKCode is the HTTP code returned for type GetPiecesSearchOK
const GetPiecesSearchOKCode int = 200

/*GetPiecesSearchOK List of pieces

swagger:response getPiecesSearchOK
*/
type GetPiecesSearchOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Piece `json:"body,omitempty"`
}

// NewGetPiecesSearchOK creates GetPiecesSearchOK with default headers values
func NewGetPiecesSearchOK() *GetPiecesSearchOK {

	return &GetPiecesSearchOK{}
}

// WithPayload adds the payload to the get pieces search o k response
func (o *GetPiecesSearchOK) WithPayload(payload []*models.Piece) *GetPiecesSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get pieces search o k response
func (o *GetPiecesSearchOK) SetPayload(payload []*models.Piece) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPiecesSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Piece, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetPiecesSearchInternalServerErrorCode is the HTTP code returned for type GetPiecesSearchInternalServerError
const GetPiecesSearchInternalServerErrorCode int = 500

/*GetPiecesSearchInternalServerError Internal Error

swagger:response getPiecesSearchInternalServerError
*/
type GetPiecesSearchInternalServerError struct {
}

// NewGetPiecesSearchInternalServerError creates GetPiecesSearchInternalServerError with default headers values
func NewGetPiecesSearchInternalServerError() *GetPiecesSearchInternalServerError {

	return &GetPiecesSearchInternalServerError{}
}

// WriteResponse to the client
func (o *GetPiecesSearchInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
