// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostPiecesIDHandlerFunc turns a function with the right signature into a post pieces ID handler
type PostPiecesIDHandlerFunc func(PostPiecesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostPiecesIDHandlerFunc) Handle(params PostPiecesIDParams) middleware.Responder {
	return fn(params)
}

// PostPiecesIDHandler interface for that can handle valid post pieces ID params
type PostPiecesIDHandler interface {
	Handle(PostPiecesIDParams) middleware.Responder
}

// NewPostPiecesID creates a new http.Handler for the post pieces ID operation
func NewPostPiecesID(ctx *middleware.Context, handler PostPiecesIDHandler) *PostPiecesID {
	return &PostPiecesID{Context: ctx, Handler: handler}
}

/*PostPiecesID swagger:route POST /pieces/{id} postPiecesId

Update a piece

Update a piece

*/
type PostPiecesID struct {
	Context *middleware.Context
	Handler PostPiecesIDHandler
}

func (o *PostPiecesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostPiecesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
