// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutKeysIDHandlerFunc turns a function with the right signature into a put keys ID handler
type PutKeysIDHandlerFunc func(PutKeysIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutKeysIDHandlerFunc) Handle(params PutKeysIDParams) middleware.Responder {
	return fn(params)
}

// PutKeysIDHandler interface for that can handle valid put keys ID params
type PutKeysIDHandler interface {
	Handle(PutKeysIDParams) middleware.Responder
}

// NewPutKeysID creates a new http.Handler for the put keys ID operation
func NewPutKeysID(ctx *middleware.Context, handler PutKeysIDHandler) *PutKeysID {
	return &PutKeysID{Context: ctx, Handler: handler}
}

/*PutKeysID swagger:route PUT /keys/{id} putKeysId

Add or update a key

Add or update a key

*/
type PutKeysID struct {
	Context *middleware.Context
	Handler PutKeysIDHandler
}

func (o *PutKeysID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutKeysIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
