// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutPartsIDOKCode is the HTTP code returned for type PutPartsIDOK
const PutPartsIDOKCode int = 200

/*PutPartsIDOK Part updated

swagger:response putPartsIdOK
*/
type PutPartsIDOK struct {
}

// NewPutPartsIDOK creates PutPartsIDOK with default headers values
func NewPutPartsIDOK() *PutPartsIDOK {
	return &PutPartsIDOK{}
}

// WriteResponse to the client
func (o *PutPartsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutPartsIDForbiddenCode is the HTTP code returned for type PutPartsIDForbidden
const PutPartsIDForbiddenCode int = 403

/*PutPartsIDForbidden Unauthorized

swagger:response putPartsIdForbidden
*/
type PutPartsIDForbidden struct {
}

// NewPutPartsIDForbidden creates PutPartsIDForbidden with default headers values
func NewPutPartsIDForbidden() *PutPartsIDForbidden {
	return &PutPartsIDForbidden{}
}

// WriteResponse to the client
func (o *PutPartsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
