// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutMusiciansIDHandlerFunc turns a function with the right signature into a put musicians ID handler
type PutMusiciansIDHandlerFunc func(PutMusiciansIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutMusiciansIDHandlerFunc) Handle(params PutMusiciansIDParams) middleware.Responder {
	return fn(params)
}

// PutMusiciansIDHandler interface for that can handle valid put musicians ID params
type PutMusiciansIDHandler interface {
	Handle(PutMusiciansIDParams) middleware.Responder
}

// NewPutMusiciansID creates a new http.Handler for the put musicians ID operation
func NewPutMusiciansID(ctx *middleware.Context, handler PutMusiciansIDHandler) *PutMusiciansID {
	return &PutMusiciansID{Context: ctx, Handler: handler}
}

/*PutMusiciansID swagger:route PUT /musicians/{id} putMusiciansId

Add or update a musician

Add or update a musician

*/
type PutMusiciansID struct {
	Context *middleware.Context
	Handler PutMusiciansIDHandler
}

func (o *PutMusiciansID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutMusiciansIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
