// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/opus47/cloud/api/models"
)

// NewPutPiecesParams creates a new PutPiecesParams object
// no default values defined in spec.
func NewPutPiecesParams() PutPiecesParams {

	return PutPiecesParams{}
}

// PutPiecesParams contains all the bound params for the put pieces operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutPieces
type PutPiecesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The piece to add or update
	  Required: true
	  In: body
	*/
	Data *models.Piece
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutPiecesParams() beforehand.
func (o *PutPiecesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Piece
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("data", "body"))
			} else {
				res = append(res, errors.NewParseError("data", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Data = &body
			}
		}

	} else {
		res = append(res, errors.Required("data", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
