// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutRecordingsHandlerFunc turns a function with the right signature into a put recordings handler
type PutRecordingsHandlerFunc func(PutRecordingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutRecordingsHandlerFunc) Handle(params PutRecordingsParams) middleware.Responder {
	return fn(params)
}

// PutRecordingsHandler interface for that can handle valid put recordings params
type PutRecordingsHandler interface {
	Handle(PutRecordingsParams) middleware.Responder
}

// NewPutRecordings creates a new http.Handler for the put recordings operation
func NewPutRecordings(ctx *middleware.Context, handler PutRecordingsHandler) *PutRecordings {
	return &PutRecordings{Context: ctx, Handler: handler}
}

/*PutRecordings swagger:route PUT /recordings putRecordings

Add or update a recording

Add or update a recording

*/
type PutRecordings struct {
	Context *middleware.Context
	Handler PutRecordingsHandler
}

func (o *PutRecordings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutRecordingsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
