// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutComposersIDHandlerFunc turns a function with the right signature into a put composers ID handler
type PutComposersIDHandlerFunc func(PutComposersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutComposersIDHandlerFunc) Handle(params PutComposersIDParams) middleware.Responder {
	return fn(params)
}

// PutComposersIDHandler interface for that can handle valid put composers ID params
type PutComposersIDHandler interface {
	Handle(PutComposersIDParams) middleware.Responder
}

// NewPutComposersID creates a new http.Handler for the put composers ID operation
func NewPutComposersID(ctx *middleware.Context, handler PutComposersIDHandler) *PutComposersID {
	return &PutComposersID{Context: ctx, Handler: handler}
}

/*PutComposersID swagger:route PUT /composers/{id} putComposersId

Add or update a composer

Add or update a composer

*/
type PutComposersID struct {
	Context *middleware.Context
	Handler PutComposersIDHandler
}

func (o *PutComposersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutComposersIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
