// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutComposersIDOKCode is the HTTP code returned for type PutComposersIDOK
const PutComposersIDOKCode int = 200

/*PutComposersIDOK Composer updated

swagger:response putComposersIdOK
*/
type PutComposersIDOK struct {
}

// NewPutComposersIDOK creates PutComposersIDOK with default headers values
func NewPutComposersIDOK() *PutComposersIDOK {

	return &PutComposersIDOK{}
}

// WriteResponse to the client
func (o *PutComposersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutComposersIDForbiddenCode is the HTTP code returned for type PutComposersIDForbidden
const PutComposersIDForbiddenCode int = 403

/*PutComposersIDForbidden Unauthorized

swagger:response putComposersIdForbidden
*/
type PutComposersIDForbidden struct {
}

// NewPutComposersIDForbidden creates PutComposersIDForbidden with default headers values
func NewPutComposersIDForbidden() *PutComposersIDForbidden {

	return &PutComposersIDForbidden{}
}

// WriteResponse to the client
func (o *PutComposersIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
