// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutPiecesIDOKCode is the HTTP code returned for type PutPiecesIDOK
const PutPiecesIDOKCode int = 200

/*PutPiecesIDOK Piece updated

swagger:response putPiecesIdOK
*/
type PutPiecesIDOK struct {
}

// NewPutPiecesIDOK creates PutPiecesIDOK with default headers values
func NewPutPiecesIDOK() *PutPiecesIDOK {
	return &PutPiecesIDOK{}
}

// WriteResponse to the client
func (o *PutPiecesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutPiecesIDForbiddenCode is the HTTP code returned for type PutPiecesIDForbidden
const PutPiecesIDForbiddenCode int = 403

/*PutPiecesIDForbidden Unauthorized

swagger:response putPiecesIdForbidden
*/
type PutPiecesIDForbidden struct {
}

// NewPutPiecesIDForbidden creates PutPiecesIDForbidden with default headers values
func NewPutPiecesIDForbidden() *PutPiecesIDForbidden {
	return &PutPiecesIDForbidden{}
}

// WriteResponse to the client
func (o *PutPiecesIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
