// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutRecordingsIDOKCode is the HTTP code returned for type PutRecordingsIDOK
const PutRecordingsIDOKCode int = 200

/*PutRecordingsIDOK Recording updated

swagger:response putRecordingsIdOK
*/
type PutRecordingsIDOK struct {
}

// NewPutRecordingsIDOK creates PutRecordingsIDOK with default headers values
func NewPutRecordingsIDOK() *PutRecordingsIDOK {

	return &PutRecordingsIDOK{}
}

// WriteResponse to the client
func (o *PutRecordingsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutRecordingsIDForbiddenCode is the HTTP code returned for type PutRecordingsIDForbidden
const PutRecordingsIDForbiddenCode int = 403

/*PutRecordingsIDForbidden Unauthorized

swagger:response putRecordingsIdForbidden
*/
type PutRecordingsIDForbidden struct {
}

// NewPutRecordingsIDForbidden creates PutRecordingsIDForbidden with default headers values
func NewPutRecordingsIDForbidden() *PutRecordingsIDForbidden {

	return &PutRecordingsIDForbidden{}
}

// WriteResponse to the client
func (o *PutRecordingsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
