// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Performer performer
// swagger:model Performer
type Performer struct {

	// id
	ID string `json:"id,omitempty"`

	// musician
	Musician string `json:"musician,omitempty"`

	// part
	Part string `json:"part,omitempty"`
}

// Validate validates this performer
func (m *Performer) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Performer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Performer) UnmarshalBinary(b []byte) error {
	var res Performer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
