// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Performance performance
// swagger:model Performance
type Performance struct {

	// date
	Date string `json:"date,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// performers
	Performers []*Performer `json:"performers"`

	// piece Id
	PieceID string `json:"pieceId,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this performance
func (m *Performance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePerformers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Performance) validatePerformers(formats strfmt.Registry) error {

	if swag.IsZero(m.Performers) { // not required
		return nil
	}

	for i := 0; i < len(m.Performers); i++ {
		if swag.IsZero(m.Performers[i]) { // not required
			continue
		}

		if m.Performers[i] != nil {
			if err := m.Performers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("performers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Performance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Performance) UnmarshalBinary(b []byte) error {
	var res Performance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
