// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Piece piece
// swagger:model Piece
type Piece struct {

	// catalog
	Catalog string `json:"catalog,omitempty"`

	// cfirst
	Cfirst string `json:"cfirst,omitempty"`

	// clast
	Clast string `json:"clast,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// movements
	Movements PieceMovements `json:"movements"`

	// parts
	Parts PieceParts `json:"parts"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this piece
func (m *Piece) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Piece) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Piece) UnmarshalBinary(b []byte) error {
	var res Piece
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
