// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Recording recording
// swagger:model Recording
type Recording struct {

	// file
	File string `json:"file,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// movement
	Movement string `json:"movement,omitempty"`

	// number
	Number int64 `json:"number,omitempty"`

	// performance
	Performance string `json:"performance,omitempty"`
}

// Validate validates this recording
func (m *Recording) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Recording) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recording) UnmarshalBinary(b []byte) error {
	var res Recording
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
